name: Initialize New Project

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Project Name'
        required: true
        default: 'MyArduinoProject'
      language:
        description: "Target Language"
        required: true
        type: choice
        options:
          - c
          - cpp
      mcu:
        description: 'Target controller'
        required: true
        type: choice
        options:
          - atmega328p
          - esp32
jobs:
  generate-enviroment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate Project Structure
        run: |
          mkdir -p src scripts   

          cat <<EOF> src/main.${{github.event.inputs.language}}
          int main()\n
          {return 0;}
          EOF
          cat <<EOF> CMakeLists.txt 
          cmake_minimum_required(VERSION 3.10)
          project(${{github.event.inputs.project_name}} LANGUAGES C CXX)
          set(MCU ${{github.event.inputs.mcu}})
          
          if(MCU STREQUAL "atmega328p")
            set(CMAKE_C_FLAGS "-mmcu=\${MCU} -Os -Wall")
            set(CMAKE_CXX_FLAGS "-mmcu=\${MCU} -Os -Wall")
            set(F_CPU 16000000UL)
            add_definitions(-DF_CPU=\${F_CPU})
          endif()
          add_executable(\${PROJECT_NAME} src/main.${{ github.event.inputs.language }})

          if(MCU STREQUAL "atmega328p")
            add_custom_command(TARGET \${PROJECT_NAME} POST_BUILD
              COMMAND \${CMAKE_OBJCOPY} -O ihex -R .eeprom \${PROJECT_NAME} \${PROJECT_NAME}.hex
              COMMENT "Generating HEX file for upload")
          endif()

          EOF

          cat <<EOF > shell.nix
          { pkgs ? import <nixpkgs> {} }:
          pkgs.mkShell {
            buildInputs = with pkgs; [
              cmake
              gnumake
              avrdude
              pkgsCross.avr.buildPackages.gcc
            ];
            shellHook = ''
              echo " Shell-Nix activated for ${{ github.event.inputs.mcu }} "
            '';
          }
          EOF

          cat <<EOF > scripts/build.sh

          mkdir -p build && cd build

          cmake..
          make -j\${nproc}
          EOF

          cat <<EOF > scripts/deploy.sh
          PORT=\$(ls /dev/ttyACM* /dev/ttyUSB* 2>/dev/null | head -n 1)
          if [ -z "\$PORT" ]; then
              echo "Error: No usb connection"
              exit 1
          fi
          echo "Flash on \$PORT..."
          avrdude -v -p atmega328p -c arduino -P "\$PORT" -b 115200 -D -U flash:w:build/${{ github.event.inputs.project_name }}.hex:i
          EOF


          chmod +x scripts/*.sh

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Initialize ${{ github.event.inputs.project_name }} structure"
          git push